### ISSUE TITLE
About the AnimixPlay support

### ISSUE THREAD

**Issue by nightbrd** [FarukGamer/cinema#15]
Hey, I'm submitting this new issue due to the announcement that Animix has [shut down due to problems in the scrapper system](https://twitter.com/AniMixPlay/status/1606200712454471680).
If possible and if anyone's able to, will any of the addon's maintainers be adding support for another website like it? Thank you, and no worries if this isn't doable at the moment.

**Comment by FarukGamer** [comment]
AnimixPlay is now replaced with YugenAnime. https://github.com/FarukGamer/cinema/commit/22a744aca967b76a30c577d6db958978640aaa64

**Comment by nightbrd** [comment]
I see, very well. Thank you a ton for your work!
