### ISSUE TITLE
YugenAnime Domain Change

### ISSUE THREAD

**Issue by MiniMelt** [FarukGamer/cinema#19]
Yugen appears to have had a new domain change. 
I attempted to update the two lines with the new domain but it doesn't seem to fix the issue.

**Comment by FarukGamer** [comment]
Hi, I'm already aware that the domain has changed again, but also the way the data is gathered has changed. I can't manage to solve the problem because it has a mechanism inside that can't be bypassed.

**Comment by MiniMelt** [comment]
Thanks for the update! I hope there is a good option in the future as watching anime without having to host on a webserver is really helpful. 
Appreciate all you do.
