### ISSUE TITLE
Remove cinema_construct from maps_ducttape

### ISSUE THREAD

**Issue by chev2** [FarukGamer/cinema#20]
Greetings,

I am the creator and maintainer of the Cinema map cinema_construct. Today I released an update for the map that skips the `theater_door` patch for Cinema-based gamemodes like `cinema_modded`. My apologies for not applying this sooner.

With this change, I believe the file `gamemode/maps_ducttape/cinema_construct.lua` is no longer necessary. Feel free to test these changes I've made to ensure they work for you as well.

Thank you! :+1:

**Comment by Xeddius** [comment]
@chev2 Just want to say I'm a huge fan of your map btw.

**Comment by FarukGamer** [comment]
Changed with commit https://github.com/FarukGamer/cinema/commit/0b556c69ff1b004bd12f0e197e7c740a56cf8b46

- Closing Issue
